### ISSUE TITLE
Pagina em Branco

### ISSUE THREAD

**Issue by Shadayy** [CajuCLC/MageBR-Boleto_Bancario_Magento#16]
Estou com dificuldade em utilizar o módulo do boleto bancário.
Efetuei a instalacao pelo Magento Connect, limpei o cache e coloquei os arquivos dentro das pastas, limpei o cache denovo, mas quando finalizo o pedido ele me redireciona para uma página vazia com a URL meusite.com/BoletoBancario/standard/redirect/ 

Não encontro solução para este problema, o que posso fazer ?

**Comment by CajuCLC** [comment]
Verifique os logs do seu web service.
Att.

**Comment by Shadayy** [comment]
[12-Sep-2015 00:24:22 UTC] PHP Fatal error:  Call to a member function getMethodInstance() on a non-object in /home/ludew149/public_html/anazulma.com/desenvolvimento2/includes/src/Mage_Payment_Helper_Data.php on line 119
[12-Sep-2015 00:30:19 UTC] PHP Fatal error:  Class 'Mage_Payment_Helper_Data' not found in /home/ludew149/public_html/anazulma.com/desenvolvimento2/app/Mage.php on line 547
[12-Sep-2015 00:33:35 UTC] PHP Fatal error:  Call to a member function getMethodInstance() on a non-object in /home/ludew149/public_html/anazulma.com/desenvolvimento2/includes/src/Mage_Payment_Helper_Data.php on line 119
[12-Sep-2015 00:43:08 UTC] PHP Fatal error:  Call to a member function getMethodInstance() on a non-object in /home/ludew149/public_html/anazulma.com/desenvolvimento2/includes/src/Mage_Payment_Helper_Data.php on line 119

**Comment by Shadayy** [comment]
[12-Sep-2015 00:24:22 UTC] PHP Fatal error:  Call to a member function getMethodInstance() on a non-object in meuSite/includes/src/Mage_Payment_Helper_Data.php on line 119
[12-Sep-2015 00:30:19 UTC] PHP Fatal error:  Class 'Mage_Payment_Helper_Data' not found in meuSite/app/Mage.php on line 547
[12-Sep-2015 00:33:35 UTC] PHP Fatal error:  Call to a member function getMethodInstance() on a non-object in meuSite/includes/src/Mage_Payment_Helper_Data.php on line 119
[12-Sep-2015 00:43:08 UTC] PHP Fatal error:  Call to a member function getMethodInstance() on a non-object in meuSite/includes/src/Mage_Payment_Helper_Data.php on line 119

**Comment by CajuCLC** [comment]
Você limpou a compilação depois de instalar? Limpou o cache?
Esses erros ai nem aparenta ser do módulo.
Recomendo verificar com seu developer para confirmar que o módulo foi realmente instalado e que está rodando tudo certo.
Desative qualquer tipo de cache, incluindo a compilação, teste no tema base e utilize o checkout padrão do Magento para identificar problemas.

**Comment by Shadayy** [comment]
Foi eu mesmo quem fez a instalação do módulo.
Realizei as seguintes etapas:
1 - Desabilitei Compilação
2 - Limpei cache (via Magento Admin e FTP) incluindo a session
3 - Instalei o módulo via Magento Connect
4 - Movi os seguintes arquivos para a pasta do meu tema
/app/design/frontend/base/default/template/BoletoBancario/standard/
/app/design/frontend/base/default/template/BoletoBancario/BoletoBancario.phtml
/skin/frontend/base/default/images/cards/
/skin/frontend/base/default/images/boleto/
5- Limpei novamente o cache

Aqui o Stack Trace mais detalhado:
exception 'Mage_Core_Exception' with message 'Tipo de bloco inválido: Mage_Megamenu_Block_List' in meuSite/app/Mage.php:595
Stack trace:
#0 meuSite/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Tipo de bloco i...')
#1 meuSite/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('megamenu/list', Array)
#2 meuSite/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('megamenu/list', 'megamenu.list.t...')
#3 meuSite/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('megamenu/list', 'megamenu.list.t...')
#4 meuSite/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 meuSite/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 meuSite/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#7 meuSite/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#8 meuSite/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#9 meuSite/app/code/core/Mage/Checkout/controllers/CartController.php(177): Mage_Core_Controller_Varien_Action->loadLayout()
#10 meuSite/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction()
#11 meuSite/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 meuSite/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 meuSite/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 meuSite/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 meuSite/index.php(87): Mage::run('', 'store')
#16 {main}

**Comment by CajuCLC** [comment]
Mage_Megamenu_Block_List

Isso é de outro módulo.
